# Base Rails configuration
AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - tmp/**

# Avoid methods longer than 30 lines of code
MethodLength:
  Max: 30

Encoding:
  Enabled: false

LineLength:
  Enabled: false
  Max: 80

Metrics/AbcSize:
  Max: 30

Style/AccessorMethodName:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: false
